name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag for the release'
        required: true
        default: 'v1.0.0'
      release_name:
        description: 'Release name'
        required: true
        default: 'Release v1.0.0'

jobs:
  build:
    runs-on: ubuntu-16.04  # 使用较旧的 Ubuntu 版本，确保 glibc 版本兼容

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build executable with PyInstaller
      run: |
        pyinstaller ./api/main.py \
        --onefile \
        --name=yeschat2api \
        --add-data='.env:.'
    
    - name: List build files
      run: ls -R  # 递归列出当前目录下的所有文件

    - name: Upload to GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'dist/yeschat2api*'  # 生成的文件路径
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.event.inputs.tag_name }}
        name: ${{ github.event.inputs.release_name }}
        body: |
          Manual release from GitHub Actions.
