name: Build and Release

# 定义手动触发
on:
  workflow_dispatch:  # 手动触发工作流
    inputs:
      tag_name:
        description: 'Tag for the release'  # 输入标签名称
        required: true
        default: 'v1.0.0'
      release_name:
        description: 'Release name'  # 输入发布名称
        required: true
        default: 'Release v1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # 选择你需要的Python版本

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run build script
      run: python build.py

    - name: List build files
      run: ls -R  # 递归列出当前目录下的所有文件

    - name: Upload to GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'path/to/your/artifact/*'  # 替换为构建生成的文件路径
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.event.inputs.tag_name }}
        name: ${{ github.event.inputs.release_name }}
        body: |
          Manual release from GitHub Actions.
